
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=https://api.yourdomain.com

  backend:
    build:
      context: https://github.com/BarnaTB/leave-management-backend.git
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/leaves
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=leaves
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
